spring:
    datasource:
        name: test
        #url: jdbc:h2:~/.h2db/nutz-starter;MODE=MYSQL
        url: jdbc:mysql://139.159.228.38:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: G00dl^ck
        # 使用druid数据源
        type: org.nutz.dao.impl.SimpleDataSource
        #driver-class-name: org.h2.Driver
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
   # jackson: #已使用nutzjson替代
    #    date-format: yyyy-MM-dd HH:mm:ss Z
     #   time-zone: GMT+8     #此处有巨坑 jackson就是要按照utc时间来给你序列化咋滴!!  
logging:
  level:
    root: info
    org.nutz: debug
    demo: debug
management:
  security:
    enabled: false
nutz:
    json:
      date-format: yyyy-MM-dd HH:mm:ss z
    dao:
        runtime:
          add-column: true
          check-index: true
          delete-column: true
          foce-create: false #此配置为true则每次均会删表重建
          create: true
          migration: true
          basepackage: demo
        sqlmanager:
          paths:
            - sqls/acl/user.sql
        
